#!/bin/bash
# ============================================================
# scripts/install/configure-env.sh
# Writes /etc/emart/login.env and /etc/emart/cart.env
# Uses the SAME JWT_SECRET in both (critical).
#
# Run:  sudo bash scripts/install/configure-env.sh
# ============================================================
set -euo pipefail

GRN='\033[0;32m'; YEL='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
ok()  { echo -e "${GRN}[ OK ]${NC}  $*"; }
die() { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

[[ $EUID -ne 0 ]] && die "Run as root"

echo "=== Emart Environment Configuration ==="
echo ""
read -rp "Login service MONGO_URI (mongodb://emart_user:PASS@localhost:27017/userdb?authSource=userdb): " LOGIN_MONGO_URI
read -rp "Cart service  MONGO_URI (mongodb://emart_user:PASS@localhost:27017): " CART_MONGO_URI
read -rp "Redis password: " REDIS_PASSWORD
echo ""

# Generate shared JWT secret (same for both services)
JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n')
ok "Generated JWT_SECRET (identical in both env files)"

# Generate service-to-service secret (Payment → Notification)
SVCKEY=$(openssl rand -hex 24)
ok "Generated SERVICE_SECRET (shared between payment.env and notification.env)"

# ── Write login.env ────────────────────────────────────────
cat > /etc/emart/login.env <<EOF
# Login Service — generated by configure-env.sh
SPRING_PROFILE=prod
MONGO_URI=${LOGIN_MONGO_URI}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION_MS=3600000
SERVER_PORT=8080
EOF
chmod 640 /etc/emart/login.env
chown root:emart /etc/emart/login.env
ok "Written: /etc/emart/login.env"

# ── Write cart.env ─────────────────────────────────────────
cat > /etc/emart/cart.env <<EOF
# Cart Service — generated by configure-env.sh
APP_ENV=prod
APP_NAME=emart-cart-service
APP_VERSION=1.0.0
GIN_MODE=release

SERVER_PORT=8081

MONGO_URI=${CART_MONGO_URI}
MONGO_DATABASE=cart

REDIS_ADDR=localhost:6379
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_DB=0
REDIS_CART_TTL=168h

# Must match login.env JWT_SECRET exactly
JWT_SECRET=${JWT_SECRET}

SYNC_INTERVAL=30s
SYNC_BATCH_SIZE=100
EOF
chmod 640 /etc/emart/cart.env
chown root:emart /etc/emart/cart.env
ok "Written: /etc/emart/cart.env"

echo ""
echo "══════════════════════════════════════════════════════"
ok "Environment configured!"
echo "══════════════════════════════════════════════════════"
echo ""
echo "Next step:"
echo "  sudo bash scripts/deploy/deploy-all.sh"

# ── Write books.env ─────────────────────────────────────────
echo ""
read -rp "Books PostgreSQL URI (postgresql://emart_books:PASS@localhost:5432/booksdb): " BOOKS_DB_URI

cat > /etc/emart/books.env <<BOOKSENV
# Books Service — generated by configure-env.sh
NODE_ENV=production
APP_NAME=emart-books-service
APP_VERSION=1.0.0

PORT=8082

DB_HOST=localhost
DB_PORT=5432
DB_NAME=booksdb
DB_USER=emart_books
DB_PASSWORD=$(echo "$BOOKS_DB_URI" | sed 's|.*://[^:]*:\([^@]*\)@.*|\1|')

# Must match login.env and cart.env JWT_SECRET exactly
JWT_SECRET=${JWT_SECRET}

LOG_LEVEL=warn
LOG_FILE=/var/log/emart/books-service.log
BOOKSENV

chmod 640 /etc/emart/books.env
chown root:emart /etc/emart/books.env
ok "Written: /etc/emart/books.env"

# ── Write course.env ─────────────────────────────────────────
echo ""
read -rsp "Course Service DB password (for coursedb / emart_course user): " COURSE_DB_PASS
echo ""

cat > /etc/emart/course.env <<COURSEENV
# Course Service — generated by configure-env.sh
APP_ENV=production
APP_NAME=emart-course-service
APP_VERSION=1.0.0

PORT=8083

# PostgreSQL — coursedb
DB_HOST=localhost
DB_PORT=5432
DB_NAME=coursedb
DB_USER=emart_course
DB_PASSWORD=${COURSE_DB_PASS}

# JWT — MUST be identical in login.env, cart.env, books.env, course.env
JWT_SECRET=${JWT_SECRET}

# Logging
LOG_LEVEL=warn
LOG_JSON=false
COURSEENV

chmod 640 /etc/emart/course.env
chown root:emart /etc/emart/course.env
ok "Written: /etc/emart/course.env"

# ── Write payment.env ─────────────────────────────────────────
echo ""
read -rsp "Payment Service DB password (for paymentdb / emart_payment user): " PAY_DB_PASS
echo ""

cat > /etc/emart/payment.env <<PAYENV
# Payment Service — generated by configure-env.sh
APP_ENV=production
APP_NAME=emart-payment-service
APP_VERSION=1.0.0

PORT=8084

# PostgreSQL — paymentdb
DB_HOST=localhost
DB_PORT=5432
DB_NAME=paymentdb
DB_USER=emart_payment
DB_PASSWORD=${PAY_DB_PASS}

# JWT — MUST be identical in login.env, cart.env, books.env, course.env, payment.env
JWT_SECRET=${JWT_SECRET}

# Cart Service URL — for fetching cart and clearing after payment
CART_SERVICE_URL=http://localhost:8081

# Notification Service — Phase 9 integration (emails after payment)
NOTIFICATION_SERVICE_URL=http://localhost:8088
NOTIFICATION_SERVICE_SECRET=${SVCKEY}

# Payment simulation
PAYMENT_SIMULATION=true
PAYMENT_SUCCESS_RATE=0.95

# Logging
LOG_LEVEL=WARN
JPA_SHOW_SQL=false
PAYENV

chmod 640 /etc/emart/payment.env
chown root:emart /etc/emart/payment.env
ok "Written: /etc/emart/payment.env"

# ── Write profile.env ─────────────────────────────────────────
echo ""
read -rsp "Profile Service DB password (for profiledb / emart_profile user): " PROF_DB_PASS
echo ""

cat > /etc/emart/profile.env <<PROFILEENV
# Profile Service — generated by configure-env.sh
APP_ENV=production
PORT=8086

DB_HOST=localhost
DB_PORT=5432
DB_NAME=profiledb
DB_USER=emart_profile
DB_PASSWORD=${PROF_DB_PASS}

# JWT — MUST be identical across ALL services
JWT_SECRET=${JWT_SECRET}

LOG_LEVEL=warn
PROFILEENV

chmod 640 /etc/emart/profile.env
chown root:emart /etc/emart/profile.env
ok "Written: /etc/emart/profile.env"

# ── Write notification.env ────────────────────────────────────
echo ""
info "SMTP setup for Notification Service."
info "Leave SMTP_HOST blank to use Ethereal test email (dev only)."
read -rp  "SMTP Host (e.g. smtp.sendgrid.net) [leave blank for test]: " SMTP_HOST
read -rp  "SMTP Port [587]: " SMTP_PORT
SMTP_PORT=${SMTP_PORT:-587}
read -rp  "SMTP User: " SMTP_USER
read -rsp "SMTP Password: " SMTP_PASS
echo ""
read -rp  "From email [noreply@emart.com]: " FROM_EMAIL
FROM_EMAIL=${FROM_EMAIL:-noreply@emart.com}
# SVCKEY was already generated at startup — same value used in payment.env

cat > /etc/emart/notification.env <<NOTIFENV
# Notification Service — generated by configure-env.sh
APP_ENV=production
PORT=8088

# JWT — MUST be identical across ALL services
JWT_SECRET=${JWT_SECRET}

# Internal service-to-service secret (Payment → Notification)
SERVICE_SECRET=${SVCKEY}

# SMTP — leave blank to use Ethereal test email in development
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
FROM_EMAIL=${FROM_EMAIL}

LOG_LEVEL=warn
NOTIFENV

chmod 640 /etc/emart/notification.env
chown root:emart /etc/emart/notification.env
ok "Written: /etc/emart/notification.env"
